
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SALON = 14;
  public static final int HORARIO = 16;
  public static final int COMILLAS = 6;
  public static final int ID = 10;
  public static final int ASIGNAR = 17;
  public static final int COMA = 11;
  public static final int EOF = 0;
  public static final int EDIFICIO = 13;
  public static final int PARENTESIS_C = 4;
  public static final int error = 1;
  public static final int NUMERO = 5;
  public static final int USUARIO = 8;
  public static final int ESTUDIANTE = 2;
  public static final int PARENTESIS_A = 3;
  public static final int PUNTOCOMA = 7;
  public static final int CATEDRATICO = 12;
  public static final int CURSO = 15;
  public static final int STRING_S = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ESTUDIANTE",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "NUMERO",
  "COMILLAS",
  "PUNTOCOMA",
  "USUARIO",
  "STRING_S",
  "ID",
  "COMA",
  "CATEDRATICO",
  "EDIFICIO",
  "SALON",
  "CURSO",
  "HORARIO",
  "ASIGNAR"
  };
}

